<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>例外(exceptions)</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

 </head>
 <body class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="language.errors.php7.html">« PHP 7 でのエラー</a></li>
      <li style="float: right;"><a href="language.exceptions.extending.html">例外を拡張する »</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="langref.html">言語リファレンス</a></li>
    <li>例外(exceptions)</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="language.exceptions" class="chapter">
 <h1>例外(exceptions)</h1>
<h2>目次</h2><ul class="chunklist chunklist_chapter"><li><a href="language.exceptions.extending.html">例外を拡張する</a></li></ul>

   
 

  <div class="simplesect" id="language.exceptions.introduction">
   <p class="para">
    PHP は、他のプログラミング言語に似た例外モデルを有しています。
    PHP 内で例外が投げられ (<a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> され)、それが
    捕捉され (<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> され) ます。発生した例外を
    捕捉するには、コードを <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> ブロックで囲みます。
    各 <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> ブロックには、対応する <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>
    ブロックあるいは <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックが存在する必要があります。
   </p>
   <p class="para">
    例外がスローされ、現在の関数スコープに <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックがなかった場合、
    その例外は、マッチする <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>
    ブロックが見つかるまで関数のコールスタックを &quot;遡って&quot; いきます。
    その途中で見つかった全ての <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックが実行されます。
    グローバルスコープに遡るまで全てのコールスタックを探しても、
    マッチする <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックが見つからない場合は、
    グローバルな例外ハンドラが設定されていない限り Fatal Error となり、
    プログラムが終了します。
   </p>
   <p class="para">
    スローされるオブジェクトは、<a href="class.exception.html" class="classname">Exception</a> クラスあるいは
    <a href="class.exception.html" class="classname">Exception</a> のサブクラスのインスタンスでなければなりません。
    それ以外のオブジェクトをスローしようとすると
    PHP の Fatal Error が発生します。
   </p>
   <p class="para">
    PHP 8.0.0 以降では、<a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> キーワードは式として扱えるようになり、
    様々なコンテクストで使えるようになりました。
    これより前のバージョンでは、<a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> は文であり、
    それが現れる行でだけでしか使えませんでした。
   </p>

  </div>

  <div class="simplesect" id="language.exceptions.catch">
   <h3 class="title"><code class="literal">catch</code></h3>
   <p class="para">
    <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックは、スローされた例外にどのように反応するかを定義します。
    <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックは、扱えるひとつ以上の例外またはエラー型を定義します。
    そして、オプションで例外を代入できる変数も定義できます。
    (PHP 8.0.0 より前のバージョンでは、この変数定義は必須です)
    スローされた例外またはエラーにマッチする最初の <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>
    ブロックが、そのオブジェクトを処理します。
   </p>
   <p class="para">
    さまざまな型の例外を捕捉するために
    複数の <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックを使用することができます。
    通常の実行時 (<a href="language.exceptions.html" class="link"><code class="literal">try</code></a> ブロック内で例外が投げられなかった
    場合) は、<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>
    ブロック内は処理されず、それ以降から処理が続けられます。
    <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックの中から例外を <a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> する
    (あるいは <a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> しなおす) こともできます。
    <a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> し直さない場合、その <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックの後から処理が続けられます。
   </p>
   <p class="para">
    例外が投げられた場合、その命令に続くコードは実行されず、
    PHP は最初にマッチする <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックを探します。
    例外が捕捉されない場合、PHP は &quot;<code class="literal">Uncaught Exception ...</code>&quot;
    というメッセージとともに
    致命的なエラー(fatal error)を発行します。
    ただし、<span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span> でハンドラが
    定義されている場合を除きます。
   </p>
   <p class="para">
    PHP 7.1.0 以降では、<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロック で 複数の例外を 
    パイプ文字 (<code class="literal">|</code>) を使って指定できるようになりました。
    これは、異なるクラス階層からの例外を同時に扱う必要がある場合に有用です。
   </p>
   <p class="para">
    PHP 8.0.0 以降では、キャッチされた例外に対応する変数はオプションになりました。
    指定されない場合、<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックは実行されるものの、
    投げられたオブジェクトへアクセスすることは出来ません。
   </p>
   <p class="para">
    <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックと <a href="function.return.html" class="link"><code class="literal">return</code></a> 文の間には注意すべき相互作用があります。
    <a href="function.return.html" class="link"><code class="literal">return</code></a> 文が <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> や <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックの内部に存在した場合でも、
    <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックは実行されます。
    さらに、<a href="function.return.html" class="link"><code class="literal">return</code></a> 文は出現した時に評価されますが、
    結果は <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックが実行された後に返されます。
    さらに、<a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックにも <a href="function.return.html" class="link"><code class="literal">return</code></a> 文が存在した場合は、
    <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックから値が返されます。
   </p>
  </div>
  <div class="simplesect" id="language.exceptions.finally">
   <h3 class="title"><code class="literal">finally</code></h3>
   <p class="para">
    <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックの後に
    <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックも指定できます。
    <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックの何かに書いたコードは、
    <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> および <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックの後で常に実行されます。
    例外がスローされたかどうかは関係ありません。
   </p>
  </div>

 <div class="simplesect" id="language.exceptions.exception-handler">
  <h3 class="title"><code class="literal">グローバルな例外ハンドラ</code></h3>
  <p class="para">
   例外がグローバルスコープにまで遡った場合、
   設定されていれば、グローバルな例外ハンドラがそれをキャッチすることができます。
   他の <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックが呼び出されなかった場合に、
   <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> の代わりに呼び出される関数を
   <span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span> 関数で設定できます。
   その効果は、プログラム全体を <a href="language.exceptions.html" class="link"><code class="literal">try</code></a>-<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> ブロックで囲むことと同じです。
  </p>
 </div>

 <div class="simplesect" id="language.exceptions.notes">
   <h3 class="title">注意</h3>

   <blockquote class="note"><p><strong class="note">注意</strong>: 
    <p class="para">
     PHP の内部関数の多くは
     <a href="errorfunc.configuration.html#ini.error-reporting" class="link">エラー報告</a>
     を使っており、例外を使っているのは新しい
     <a href="language.oop5.html" class="link">オブジェクト指向</a>
     の拡張モジュールのみです。
     しかし、<a href="class.errorexception.html" class="link">ErrorException</a>
     を使えば簡単にエラーを例外に変換することができます。
     この変換テクニックが使えるのは、致命的でないエラーに限ります。
    </p>
    <div class="example" id="example-288">
     <p><strong>例3 エラーを例外に変換する</strong></p>
     <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">exceptions_error_handler</span><span style="color: #007700">(</span><span style="color: #0000BB">$severity</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$message</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$filename</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$lineno</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">ErrorException</span><span style="color: #007700">(</span><span style="color: #0000BB">$message</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">0</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$severity</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$filename</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$lineno</span><span style="color: #007700">);<br />}<br /><br /></span><span style="color: #0000BB">set_error_handler</span><span style="color: #007700">(</span><span style="color: #DD0000">'exceptions_error_handler'</span><span style="color: #007700">);<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
     </div>

    </div>
   </p></blockquote>
   <div class="tip"><strong class="tip">ヒント</strong>
    <p class="para">
     <a href="intro.spl.html" class="link">Standard PHP Library (SPL)</a>
     には<a href="spl.exceptions.html" class="link">組み込みの例外</a>が数多く用意されています。
    </p>
   </div>
  </div>

  <div class="simplesect" id="language.exceptions.examples">
   <h3 class="title">例</h3>

   <div class="example" id="example-289">
    <p><strong>例4 例外を投げるには</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'ゼロによる除算。'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'捕捉した例外:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">//&nbsp;実行は継続される<br /></span><span style="color: #007700">echo&nbsp;</span><span style="color: #DD0000">"Hello&nbsp;World\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>上の例の出力は以下となります。</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
0.2
捕捉した例外: ゼロによる除算。
Hello World
</pre></div>
    </div>
   </div>
   <div class="example" id="example-290">
    <p><strong>例5 例外処理での <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロック</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'ゼロによる除算。'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'捕捉した例外:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;finally&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"First&nbsp;finally.\n"</span><span style="color: #007700">;<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'捕捉した例外:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;finally&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"Second&nbsp;finally.\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">//&nbsp;処理を続行します<br /></span><span style="color: #007700">echo&nbsp;</span><span style="color: #DD0000">"Hello&nbsp;World\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>上の例の出力は以下となります。</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
0.2
First finally.
捕捉した例外: ゼロによる除算。
Second finally.
Hello World
</pre></div>
    </div>
   </div>
   <div class="example" id="example-291">
    <p><strong>例6 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> ブロックと <a href="function.return.html" class="link"><code class="literal">return</code></a> の相互作用</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">test</span><span style="color: #007700">()&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #DD0000">'catch'</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;finally&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #DD0000">'finally'</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />}<br /><br />echo&nbsp;</span><span style="color: #0000BB">test</span><span style="color: #007700">();<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>上の例の出力は以下となります。</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
finally
</pre></div>
    </div>
   </div>
   <div class="example" id="example-292">
    <p><strong>例7 ネストした例外</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class&nbsp;</span><span style="color: #0000BB">MyException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{&nbsp;}<br /><br />class&nbsp;</span><span style="color: #0000BB">Test&nbsp;</span><span style="color: #007700">{<br />&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;</span><span style="color: #0000BB">testing</span><span style="color: #007700">()&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">MyException</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo!'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">MyException&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;改めてスロー<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">throw&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">());<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />}<br /><br /></span><span style="color: #0000BB">$foo&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;</span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br /><br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>上の例の出力は以下となります。</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
string(4) &quot;foo!&quot;
</pre></div>
    </div>
   </div>
   <div class="example" id="example-293">
    <p><strong>例8 複数の例外ハンドリングをひとつの catch で行う</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class&nbsp;</span><span style="color: #0000BB">MyException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{&nbsp;}<br /><br />class&nbsp;</span><span style="color: #0000BB">MyOtherException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{&nbsp;}<br /><br />class&nbsp;</span><span style="color: #0000BB">Test&nbsp;</span><span style="color: #007700">{<br />&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;</span><span style="color: #0000BB">testing</span><span style="color: #007700">()&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">MyException</span><span style="color: #007700">();<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">MyException&nbsp;</span><span style="color: #007700">|&nbsp;</span><span style="color: #0000BB">MyOtherException&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">get_class</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">));<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />}<br /><br /></span><span style="color: #0000BB">$foo&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;</span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br /><br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>上の例の出力は以下となります。</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
string(11) &quot;MyException&quot;
</pre></div>
    </div>
   </div>
   <div class="example" id="example-294">
    <p><strong>例9 キャッチする時に変数を省略する</strong></p>
    <div class="example-contents"><p>PHP 8.0.0 以降でのみ許されます</p></div>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class&nbsp;</span><span style="color: #0000BB">SpecificException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{}<br /><br />function&nbsp;</span><span style="color: #0000BB">test</span><span style="color: #007700">()&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">SpecificException</span><span style="color: #007700">(</span><span style="color: #DD0000">'Oopsie'</span><span style="color: #007700">);<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">test</span><span style="color: #007700">();<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">SpecificException</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;print&nbsp;</span><span style="color: #DD0000">"A&nbsp;SpecificException&nbsp;was&nbsp;thrown,&nbsp;but&nbsp;we&nbsp;don't&nbsp;care&nbsp;about&nbsp;the&nbsp;details."</span><span style="color: #007700">;<br />}<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

   </div>
   <div class="example" id="example-295">
    <p><strong>例10 throw を 式として扱う</strong></p>
    <div class="example-contents"><p>PHP 8.0.0 以降でのみ許されます</p></div>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class&nbsp;</span><span style="color: #0000BB">SpecificException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{}<br /><br />function&nbsp;</span><span style="color: #0000BB">test</span><span style="color: #007700">()&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">do_something_risky</span><span style="color: #007700">()&nbsp;or&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'It&nbsp;did&nbsp;not&nbsp;work'</span><span style="color: #007700">);<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">test</span><span style="color: #007700">();<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;print&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">();<br />}<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

   </div>
  </div>

 </div>
</div></div></body></html>